### ISSUE TITLE
[bootstrap4] missing css, js files

### ISSUE THREAD

**Issue by anderbubble** [getnikola/nikola-themes#185] opened 2020-02-19 16:37 UTC
I just noticed that my bootstrap4-themed site is generating 404s for two files presumably referenced by the bootstrap4 theme:

- https://civilfritz.net/assets/js/bootstrap.min.js.map
- https://civilfritz.net/assets/css/bootstrap.min.css.map

I don't see anything in my files that's referencing these basenames, so it looks like the theme is calling for them but not providing them.

**Comment by Kwpolska** [comment] 2020-02-19 19:17
Issues related to `bootstrap4` should go in the main `getnikola/nikola` repo.

This one is caused by `/*# sourceMappingURL=bootstrap.min.css.map */` at the end of the “real” .js and .css files. This file can be used to aid web development, because it maps stuff in the minified file to the full, human-readable file, so that instead of everything being in `bootstrap.min.css:6`, you get a more interesting line number from `bootstrap.css`, and you can debug Bootstrap’s JS more easily. Those files are not requested unless you open the Web Inspector.

Nikola does not include those in sites, because we don’t ship the unminified files either. Most users won’t really need those, and those that do can easily add them to their own sites, or work directly with the original unminified files. And it makes no sense to add a few megabytes to everyone’s site for this. While we could theoretically patch out that line from those files, that removes the ability to verify you’ve got the right version if you ever wanted that. Closing as *won’t fix*.

**Closed by Kwpolska** 2020-02-19 19:17 UTC

**Comment by anderbubble** [comment] 2020-02-19 20:31
Understood. fwiw, I posted here because of the link at https://themes.getnikola.com/v8/bootstrap4/.

> Issues? Questions?
> You can report issues with this theme and request help via GitHub Issues.

That link goes to https://github.com/getnikola/nikola-themes/issues/new?title=%5Bbootstrap4%5D

**Comment by Kwpolska** [comment] 2020-02-19 21:17
I updated the wording and links for built-in themes in commit 3ec459b.
