### ISSUE TITLE
Some preview images are not representative of the theme

### ISSUE THREAD

**Issue by tritium21** [getnikola/nikola-themes#140] opened 2018-01-11 10:40 UTC
The preview image below is rendered incorrectly, compared to how it actually renders.

![bnw](https://user-images.githubusercontent.com/1781587/34821371-7b129674-f691-11e7-9d9e-82bda76ae3ed.png)

This is how it renders in Firefox (probably correct.)

![firefox_2018-01-11_05-38-22](https://user-images.githubusercontent.com/1781587/34821492-e868adb2-f691-11e7-9d1f-a1928892dba6.png)

**Comment by ralsina** [comment] 2018-01-11 15:46
Well, that depends on what fonts you have in the system, doesn't it?

**Comment by Kwpolska** [comment] 2018-01-11 17:34
This is caused by PhantomJS being terribly outdated. We could fix it with headless Chrome and [Puppeteer](https://github.com/GoogleChrome/puppeteer) for example.

**Comment by tritium21** [comment] 2018-01-11 22:01
I was more concerned with phantomjs apparently choosing to render text in arbitrarily wrong locations

**Comment by Kwpolska** [comment] 2018-01-11 22:02
Well, that’s what I’m talking about: PhantomJS’s engine is outdated and isn’t as good at new CSS tricks as Chrome/Firefox. Font faces chosen is irrelevant.

**Comment by Kwpolska** [comment] 2018-03-18 19:46
Fixed in commit be97dd1 by using Puppeteer. Needs one-time config and a Chrome/ium install, comes with much more accurate screenshots.

**Closed by Kwpolska** 2018-03-18 19:46 UTC
